#!/usr/bin/env bash

# Opens the github page for a repo/branch in your browser.
# https://github.com/paulirish/git-open/
#
# git open
# git open [remote] [branch]


# are we in a git repo?
git rev-parse --is-inside-work-tree &>/dev/null

if [[ $? != 0 ]]; then
  echo "Not a git repository."
  exit 1
fi

# get current branch
if [ -z "$2" ]; then
  branch=$(git symbolic-ref -q --short HEAD)
else
  branch="$2"
fi

# Make # and % characters url friendly
branch=${branch//%/%25} && branch=${branch//#/%23}

branch="${branch/feature/}"

jiraurl='https://ampersand.atlassian.net/browse'

if [ -n "$branch" ]; then
  jiraurl="${jiraurl}${branch}"
fi

# get current open browser command
case $( uname -s ) in
  Darwin)  open=open;;
  MINGW*)  open=start;;
  CYGWIN*) open=cygstart;;
  *)       open=${BROWSER:-xdg-open};;
esac

# open it in a browser
$open "$jiraurl" &> /dev/null
exit 0

